### ISSUE TITLE
fix doc

### ISSUE THREAD

**Issue by Sispheor** [Ultchad/kalliope_neuron_translate#3]
The synapse example still use the old syntax with "args".

It should be something like this:
```yml
- name: "translate-es"
    signals:
      - order: "translate {{sentence}} in Spanish"
    neurons:
      - translate:
          lang_in: "fr"
          lang_out: "es"
          sentence: "{{ sentence }}"
          say_template: "{{ result }}"
```
